import * as XLSX from 'xlsx';

/**
 * Creates an in-memory sample XLSX workbook representing the AVMAIS Implementation 2027 project
 * matching all fields from PRD Section 4, 5, and 6.
 */
export function generateSampleAvmaisWorkbook(): Uint8Array {
  const wb = XLSX.utils.book_new();

  // Sheet 1: AVMAIS_Backlog (Active items with open assessments)
  const headers = [
    'Record ID',
    'Workstream',
    'Deliverable',
    'Initiatives / Activities',
    'Workstream Lead',
    'Existing AVMAIS Owner',
    'Pearl Owner',
    'Current Priority',
    'Current Status',
    'Existing ETA',
    'Dependencies / Notes',
    'Business Value',
    'Member Impact',
    'Urgency',
    'Effort',
    'Workstream Rank',
    'Session Decision',
    'June 2027 Milestone / Outcome',
    'Team Rationale',
  ];

  const rows = [
    [
      'AVM-101',
      'Security & Compliance',
      'FedRAMP & HIPAA Readiness Audit',
      'Engage external assessor to validate veterinary record confidentiality and cryptographic data at rest controls.',
      'Arthur Dent',
      'Arthur Dent',
      'Pearl SecOps Team',
      'P0',
      'Requirements',
      'June 2027',
      'Audit charter sign-off by legal counsel',
      'High',
      'High',
      'High',
      'Large',
      1,
      'Selected',
      'Full FedRAMP readiness clearance by March 2027 to unblock state contract renewals.',
      'Non-negotiable compliance requirement for institutional veterinary association members.',
    ],
    [
      'AVM-102',
      'Security & Compliance',
      'Zero-Trust Role-Based Access Matrix',
      'Consolidate 14 legacy authorization silos into standardized unified claims token format.',
      'Arthur Dent',
      'Sarah Jenkins',
      'Marcus Chen',
      'P1',
      'Development',
      'Q1 2027',
      'Directory federation with IDP',
      'High',
      'Medium',
      'Medium',
      'Medium',
      2,
      'Selected',
      'Single Sign-on token format ready for Pearl portal integration by Jan 2027.',
      'Reduces friction for partner federation; development already 40% complete.',
    ],
    [
      'AVM-201',
      'Data Pipeline & Migration',
      'Legacy SQL Database Schema Extract & Parquet Lakehouse Sync',
      'Batch extract 18 million historical veterinary practitioner records into Apache Iceberg storage format.',
      'Britto Thomas',
      'Britto Thomas',
      'Pearl Data Engineering',
      'P0',
      'Development',
      'Q4 2026',
      'VPN connectivity to warehouse replica',
      'High',
      'High',
      'High',
      'Medium',
      1,
      'Selected',
      '18M practitioner records migrated without loss prior to holiday freeze.',
      'Foundational dependency for portal renewal and directory verification features.',
    ],
    [
      'AVM-202',
      'Data Pipeline & Migration',
      'Real-time Telemetry & Audit Stream Ingestion',
      'Kafka/PubSub streaming service for member clicks, license lookups, and accreditation verifications.',
      'Britto Thomas',
      'TBD', // PRD Section 6: Cell says TBD -> Show ownership gap
      'Pearl Cloud Architects',
      'P2',
      'Requirements',
      'TBD', // PRD Section 5: Preserve "TBD" without inventing exact date
      'Event schema catalog definition',
      'Medium',
      'Low',
      'Low',
      'Large',
      2,
      'Needs Validation',
      'Stream event evaluation deferred to secondary phase after batch migration.',
      'Currently lacks accountable internal owner (listed as TBD). Cannot prioritize without lead.',
    ],
    [
      'AVM-301',
      'Member Experience & Portal',
      'Veterinary Certification Self-Service Renewal Workflow',
      'Responsive multi-step submission portal allowing members to upload continuing education proof and pay dues.',
      'Sarah Jenkins',
      'Sarah Jenkins',
      'Pearl UX Studio',
      'P0',
      'Development',
      'June 2027 Milestone',
      'Payment gateway API keys & merchant registration',
      'High',
      'High',
      'High',
      'Medium',
      1,
      'Selected',
      'Member self-service renewals live ahead of June 2027 accreditation cycle.',
      'Primary source of association annual dues revenue and membership retention.',
    ],
    [
      'AVM-302',
      'Member Experience & Portal',
      'Directory Search & Practitioner Verification Badge',
      'Public-facing fast lookup for accredited veterinarians with geolocated clinic results.',
      'Sarah Jenkins',
      'Evelyn Reed', // PRD Section 6: Name exists without email -> Show name; leave account linking unresolved
      'Pearl Frontend Crew',
      'P1',
      'Testing',
      'Ongoing', // PRD Section 5: Preserve "Ongoing"
      'Search index warming & Elasticsearch cluster',
      'Medium',
      'High',
      'Low',
      'Small',
      2,
      'Reserve',
      'Launch public verification badge as fast-follow in Q3 2027.',
      'Valuable consumer trust signal, but renewal engine takes priority.',
    ],
    [
      'AVM-401',
      'Integration & Pearl Connectors',
      'Pearl B2B Bi-Directional Webhook Dispatcher',
      'Secure mutual TLS event bus informing Pearl partner systems of membership credential status changes.',
      'Marcus Chen',
      'Britto Thomas',
      'Marcus Chen',
      'P1',
      'Requirements',
      'Q1 2027',
      'Network egress whitelist & NAT gateway setup',
      'High',
      'Medium',
      'Medium',
      'Medium',
      1,
      'Selected',
      'Automated webhook delivery to Pearl partner systems by February 2027.',
      'Eliminates weekly manual CSV reconciliation emails between organizations.',
    ],
    [
      'AVM-402',
      'Integration & Pearl Connectors',
      'State Licensing Board API Sync Adapter',
      'Automated nightly sync with 50 jurisdiction boards to reconcile suspended or expired licenses.',
      'Marcus Chen',
      'Jordan Miles',
      'TBD',
      'P2',
      'Requirements',
      'Q3 2027',
      'State licensing format agreements',
      'Low',
      'Low',
      'Low',
      'Large',
      2,
      'Defer',
      'Re-evaluate state board automation in late 2027.',
      '50 state boards lack uniform APIs; high maintenance overhead for small benefit.',
    ],
    [
      'AVM-501',
      'Cloud Infrastructure & Ops',
      'Multi-Region Kubernetes Disaster Recovery Failover',
      'Deploy automated active-passive failover between us-east1 and us-west1 with 15-minute RTO target.',
      'Priya Patel',
      'Priya Patel',
      'Pearl Cloud Ops',
      'P1',
      'Development',
      'June 2027',
      'Cross-region database replication latency validation',
      'High',
      'Medium',
      'Medium',
      'Large',
      1,
      'Selected',
      'Multi-region failover drill passed with zero data loss.',
      'Required for 99.95% enterprise SLA commitments.',
    ],
  ];

  const wsBacklog = XLSX.utils.aoa_to_sheet([headers, ...rows]);
  XLSX.utils.book_append_sheet(wb, wsBacklog, 'AVMAIS_Backlog');

  // Sheet 2: Delivered_Items (Demonstrating multi-sheet workbook per PRD Section 5)
  const deliveredHeaders = ['Record ID', 'Workstream', 'Deliverable', 'Owner', 'Delivery Date', 'Stage'];
  const deliveredRows = [
    ['AVM-502', 'Cloud Infrastructure & Ops', 'Synthetic Uptime & API Latency APM Monitoring', 'Priya Patel', 'August 2026', 'Delivered'],
    ['AVM-103', 'Security & Compliance', 'Baseline TLS 1.3 Cipher Suite Enforcement', 'Arthur Dent', 'July 2026', 'Delivered'],
  ];
  const wsDelivered = XLSX.utils.aoa_to_sheet([deliveredHeaders, ...deliveredRows]);
  XLSX.utils.book_append_sheet(wb, wsDelivered, 'Delivered_Items');

  const out = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  return new Uint8Array(out);
}
